name: SimpleHomes2
version: ${version}
description: A Fork Of SimpleHomes But Better.
authors: [Andrew121410]

main: Main.SimpleHomes
database: false

commands:
  sethome:
    description: Set your home.
    permission: simplehomes.homes
  home:
    description: Teleport back to your set home.
    permission: simplehomes.homes
  otherhome:
    description: Teleport to another player's sethome.
    usage: "Usage: /otherhome <PlayerName> (HomeName)?"
    permission: simplehomes.otherhomes
  homelist:
    description: Get a list of homes
    aliases:
      - homes
    permission: simplehomes.homes
  delhome:
    description: Delete a home
    permission: simplehomes.homes
  shreload:
    description: Reload SimpleHomes configuration from disk
    permission: simplehomes.reload

permissions:
  simplehomes.homes:
    default: true
  simplehomes.otherhomes:
    default: op
  simplehomes.multihomes:
    default: op
  simplehomes.notify:
    default: op
  simplehomes.reload:
    default: op