name: SimpleHomes2
version: ${version}
description: A Fork Of SimpleHomes But Better.
authors: [Andrew121410]

main: Main.SimpleHomes
database: false

commands:
  sethome:
    description: Set your home.
    permission: simplehomes.home
  home:
    description: Teleport back to your set home.
    permission: simplehomes.home
  homelist:
    description: Get a list of homes
    aliases:
      - homes
    permission: simplehomes.home
  delhome:
    description: Delete a home
    permission: simplehomes.home